name: Matrix

on: push
# on: pull_request

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log node-version in current virtual machine
        run: node -v

      - uses: actions/setup-node@v1
        with:
          node-version: 6
        # This will download version 6 of node and install in VM

      - name: Log node-version
        run: node -v

  node-version-with-stratergy-matrix-key:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest] # This will run 9 times, version 6,7,8 runs in ubuntu-latest vm and other 2 vms as well
        node_version: [6, 7, 8]
      max-parallel: 2

    runs-on: ${{matrix.os}}
    steps:
      - name: Log node-version
        run: node -v

      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node_version}}
        # This will download version 6,7,8 of node and install in VM
        # This will run 3 times in ubuntu-latest vm
      - name: Log node-version
        run: node -v

  node-version-with-stratergy-matrix-key-include-exclude:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6, 7, 8]
        # This will run 9 times, version 6,7,8 runs in ubuntu-latest vm and other 2 vms as well
        # But excluding these below combinations
        exclude:
          - os: ubuntu-latest
            node_version: 6

          - os: macos-latest
            node_version: 7

        # But including these below combinations
        include:
          - os: ubuntu-latest
            node_version: 4
            is_ubuntu_8: true #This can be only used when it runs in ubuntu-latest with node_version 4

      max-parallel: 2

    runs-on: ${{matrix.os}}
    env:
      IS_UBUNTU_8: $is_ubuntu_8 #This can be only used when it runs in ubuntu-latest with node_version 4

    steps:
      - name: Log node-version
        run: node -v

      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node_version}}
        # This will download version 6,7,8 of node and install in VM including version 4 in ubuntu
        # This will run 3 times in windows-latest vm and 2 times in macos-latest and 2 times in ubuntu-latest

      - name: Log node-version
        run: |
          node -v
          echo $IS_UBUNTU_8 
          #This will be printed only  when it runs in ubuntu-latest with node_version 4
